// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:btcc/src/models/enums/tile_id.dart';
import 'package:btcc/src/models/hive/hive_castle.dart';
import 'package:btcc/src/models/hive/hive_game.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveCastleAdapter());
    registerAdapter(HiveGameAdapter());
    registerAdapter(TileIdAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HiveCastleAdapter());
    registerAdapter(HiveGameAdapter());
    registerAdapter(TileIdAdapter());
  }
}
